server:
  port: 8502
  servlet:
    context-path: /storage
    encoding:
      charset: UTF-8
spring:
  datasource:
    ds0:
      url: jdbc:mysql://10.211.55.6:3306/seata_storage_service?useUnicode=true&useSSL=false
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
seata:
  tx-service-group: my_test_tx_group
mybatis-plus:
  type-aliases-package: com.cxp.storage.pojo
  mapper-locations: classpath*:/mapper/**/*.xml
